### ISSUE TITLE
App build error

### ISSUE THREAD

**Issue by ardenor** [grafana/tutorial-environment#5]
Hi there! 

When docker-compose up runs, the app and db seem to exit. 

When attempting to docker-compose up the app alone, it gives the error:  /app: line 1: syntax error: unexpected "("

Thanks :)

**Comment by marcusolsson** [comment]
Thanks for letting us know!

I'm unable to reproduce this. Could you please share the OS you're running, and the Docker version you're using?

**Comment by bose2** [comment]
Hello,

Is Docker on Raspberry Pi 4 with Ubuntu OS supported for the tutorial environment? 

Have the following error "standard_init_linux.go:219: exec user process caused: exec format error" on container "tutorial-environment_db_1"

And Permissions error "/bin/sh: /app: Permission denied" on "tutorial-environment_app_1"

Thanks,
Ed

**Comment by LoLo2207** [comment]
> 
> 
> Hi there!
> 
> When docker-compose up runs, the app and db seem to exit.
> 
> When attempting to docker-compose up the app alone, it gives the error: /app: line 1: syntax error: unexpected "("
> 
> Thanks :)

Same here, also on a Raspberry Pi 4, but with Raspbian 10 (buster)
Can we get the source code of that binary and compile it manually? Or a new version.

Thanks

**Comment by romeomorcia** [comment]
I was able to reproduce on my raspberry PI 4B 4GB with ubuntu_server_21 installed.
Installation clean after update/upgrade did cause same issue.

Perhaps same issue can be reproduced with ubuntu server Docker image running inside the tutorial.
@marcusolsson 

On my macOS 11.4 worked like a charm.

**Comment by bitsy** [comment]
I'm also experiencing a similar issue. I'm running Docker 20.10.21 on a Raspberry Pi 3B+ running Pi OS Bullseye. I also use Portainer to manage Docker. Here's the log output I get from Portainer when the app container exits:
`/app: line 1: syntax error: unexpected "("`
The db container produces this error:
`exec /db: exec format error`

Any thoughts?

**Comment by markr111** [comment]
got this working on raspberry pi: changes in https://github.com/markr111/tutorial-environment/tree/ARM_DEMO

(not submitting as PR to grafana because it will break non-ARM architectures)

/app was compiled and bundled in the app repo as an AMD64 binary. 
Fixed by modifying the ./app Dockerfile to compile main.go instead of copying incompatible executable into docker image. Not perfect, could create a multistage docker build.

Also - the db container was exiting on rpi for the same reason (incompatible arch), docker hub has a pi-specific tns-db image which docker-compose.yml now points at (this will break tns-db on other architectures)

caveat: I haven't run the entire demo against this branch so things might still be broken - but no more errors on startup.

**Comment by andriandreo** [comment]
> /app was compiled and bundled in the app repo as an AMD64 binary.
> Fixed by modifying the ./app Dockerfile to compile main.go instead of copying incompatible executable into docker image. Not perfect, could create a multistage docker build.

Thanks for the contribution! I'm afraid I still can't get it to work properly: same `app-1  | /app: line 1: syntax error: unexpected "("` exit error from `docker compose logs app`

**Comment by markr111** [comment]
@andriandreo  - /app shouldn't exist  (it's at /src/app)

have you switched to the ARM_DEMO branch?

**Comment by andriandreo** [comment]
> have you switched to the ARM_DEMO branch?

Yes, of course, but something is wrong with the app file, that error persist
